target-version = "py39"
line-length = 100

[lint]
select = ["E", "F", "I"]
ignore = [
  "E701",
  "E402",
  "E501",
  "E712",
  "E722",
  "E731",
  "E741",
  "F401",
  "F811",
  "F841",
  "F403",
  "F405",
  "F821"
]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
docstring-code-format = false